#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

spec:
 template:
   spec:
     volumes:
      - name: mydirectory
        persistentVolumeClaim:
          claimName: mydirectory
     containers:
     - env:
       - name: spring.cloud.config.uri
         value: https://host.com
       - name: spring.cloud.config.enabled
         value: true
       - name: spring.cloud.config.profile
         value: dev
       - name: spring.cloud.config.username
         value: admin
       - name: spring.cloud.config.password
         value: admin
     - volumeMounts:
       - name: mydirectory
         mountPath: /mydirectorypath

